{% set version = "0.15" %}
{% set sha256 = "cb824ed02430136ee321e8a23ea47f8993b9a81041fff548f8c09d3863721958" %}

package:
  name: goetia
  version: {{ version }}

source:
  url: https://github.com/camillescott/goetia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Skipping py>=38 due to cppyy-related build and test failure.
  skip: True  # [osx or py<30 or py>=38]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
  host:
    - python
    - cppyy >=1.5.5
    - clangdev
    - openmp
    - zlib
    - python-clang
    - pip
    - sourmash
  run:
    - python
    - cppyy >=1.5.5
    - clangdev
    - openmp
    - zlib
    - screed
    - blessings
    - pyfiglet
    - py-cpuinfo
    - numpy
    - sourmash
    - curio
    - jsonschema

test:
  imports:
    - goetia

about:
  home: https://github.com/camillescott/goetia
  license: MIT
  license_file: LICENSE
  summary: streaming de Bruijn graph compaction and sketching.

extra:
  recipe-maintainers:
    - camillescott
    - luizirber
