{% set name = "CoolBox" %}
{% set version = "0.3.4" %}
 
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GangCaoLab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1208b6bb6ed036fa621f1795eb9d1405815ba952da040f7ea36bcdc8c1ba59c0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pairix
    - tabix
    - samtools >=1.10

test:
  imports:
    - coolbox

about:
  home: https://github.com/GangCaoLab/CoolBox
  license: GPL3
  license_file: LICENSE
  summary: Jupyter notebook based genomic data visulization toolkit.

extra:
  recipe-maintainers:
    - Nanguage
