{% set version = "0.19.7" %}

package:
  name: rust-bio-tools
  version: {{version}}

build:
  number: 0

source:
  url: https://github.com/rust-bio/rust-bio-tools/archive/v{{ version }}.tar.gz
  sha256: 79ac4f2da4aa8bbc6d30111747613bf027c19284004291fa3a082cdadcfe088b

requirements:
  build:
    - rust >=1.30
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - zlib
    - clangdev
    - gsl
    - libopenblas
    - openssl
  run:
    - zlib
    - gsl
    - starcode
    - libopenblas
    - openssl

test:
  commands:
    - rbt --help

about:
  home: https://github.com/rust-bio/rust-bio-tools
  license: MIT
  summary: |
    A growing collection of fast and secure command line utilities for dealing with NGS data
    implemented on top of Rust-Bio.
