{% set name = "godmd" %}
{% set version = "1.0.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d5595ea26bb32d4b364d27514c4c462e68294ebdafc0bc74ff0af66d458d10cd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: http://mmb.irbbarcelona.org/gitlab/adam/GOdMD/repository/archive.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
  run:

test:
  commands:
    - discrete -h

about:
  home: http://mmb.irbbarcelona.org/gitlab/adam/GOdMD
  license: Apache Software License
  license_family: APACHE
  summary: GOdMD Conformational Transitions with discrete Molecular Dynamics
  description: "GOdMD is a new method for determining pathways for conformational transitions in macromolecules based on the use of discrete molecular dynamics and biasing techniques based on a combination of essential dynamics and Maxwell-Demon sampling techniques. The method can work with high efficiency at different levels of resolution, including the atomistic one, and can help to define initial pathways for further exploration by means of more accurate atomistic molecular dynamics simulations."
