package:
  name: kissplice
  version: '2.5.4'

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-2.5.4.tar.gz"
  sha256: "d2d7b5bc550b25eabe8d7b4020fceaf36743cca3f4f191625b49cc80dbb7b2e7"

build:
  number: 0
  skip: True # [osx or py3k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - python

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
