{% set version = "0.3.1" %}
{% set name = "rosella" %}
{% set hash = "f7ff5a99dab862a3b4fe3c4b44d30c717dd88075290300a8a23226fcafe38208" %}

package:
  name: rosella
  version: {{ version }}

source:
  url: https://github.com/rhysnewell/rosella/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - rust >=1.40
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - gsl
  host:
    - gsl
    - zlib
    - blis
    - libblas
    - openblas
    - openssl
    - clangdev
  run:
    - python>=3.8
    - parallel
    - pysam>=0.16
    - samtools=1.9
    - vt
    - pkg-config
    - blis
    - zlib
    - gsl
    - starcode
    - openblas
    - libblas
    - bwa
    - minimap2
    - flight-genome
    - imageio
    - umap-learn>=0.5
    - hdbscan
    - matplotlib-base
    - numpy
    - seaborn
    - scikit-learn
    - scikit-bio
    - numba
    - biopython
    - pynndescent

test:
  commands:
    - {{ name }} --version | grep {{ version }}
    - flight -h

about:
  home: https://github.com/rhysnewell/rosella.git
  license: GPL3
  license_file: LICENSE
  summary: 'Metagenomic binning pipeline and algorithm using UMAP and HDBSCAN'
